/**
 * Module diagram generator orchestrator.
 *
 * Combines Flowchart and Sequence Diagram generators into complete markdown files
 * and persists them into `docs/diagrams/` and `.agents/diagrams/`.
 */

import { join, dirname } from "node:path";
import { writeFile, mkdir } from "node:fs/promises";
import type { DetectedModule, ExtractedSymbol, ExtractedFileDependency } from "../contracts/index.js";
import { generateModuleFlowchartDiagram } from "./flowchart_generator.js";
import { generateModuleSequenceDiagram } from "./sequence_diagram_generator.js";
import { logInformation } from "../shared_utilities/index.js";

export interface ModuleDiagramGeneratorInput {
  readonly repositoryRootPath: string;
  readonly detectedModules: DetectedModule[];
  readonly allExtractedSymbols: ExtractedSymbol[];
  readonly allExtractedDependencies: ExtractedFileDependency[];
}

/**
 * Generate a complete markdown document containing Flowchart and Sequence diagrams for a module.
 */
export function generateModuleDiagramMarkdown(
  targetModule: DetectedModule,
  allExtractedSymbols: ExtractedSymbol[],
  fileDependencies: ExtractedFileDependency[],
  allDetectedModules: DetectedModule[],
): string {
  const flowchartDiagram = generateModuleFlowchartDiagram(
    targetModule,
    allExtractedSymbols,
    fileDependencies,
    allDetectedModules,
  );

  const sequenceDiagram = generateModuleSequenceDiagram(
    targetModule,
    allExtractedSymbols,
    fileDependencies,
  );

  const lines: string[] = [];
  lines.push(`# Module Architecture & Execution Diagrams: ${targetModule.moduleName}`);
  lines.push(`<!-- Auto-generated by project-index diagram generator. Do not edit manually. -->`);
  lines.push("");
  if (targetModule.purpose) {
    lines.push(`> **Purpose**: ${targetModule.purpose}`);
    lines.push("");
  }

  lines.push("## Architectural Flowchart");
  lines.push("```mermaid");
  lines.push(flowchartDiagram);
  lines.push("```");
  lines.push("");

  lines.push("## Execution Sequence Diagram");
  lines.push("```mermaid");
  lines.push(sequenceDiagram);
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}

/**
 * Sanitize module name to produce safe filename (e.g. "source/repository_scanning" -> "source_repository_scanning").
 */
function sanitizeModuleNameForFileName(moduleName: string): string {
  return moduleName.replace(/[\/\\]/g, "_").replace(/[^a-zA-Z0-9_\-]/g, "");
}

/**
 * Automatically generate and write flowchart and sequence diagram files for all detected modules.
 */
export async function generateAllModuleDiagramFiles(
  input: ModuleDiagramGeneratorInput,
): Promise<void> {
  const { repositoryRootPath, detectedModules, allExtractedSymbols, allExtractedDependencies } = input;

  const docsDiagramsDirectory = join(repositoryRootPath, "docs", "diagrams");
  const agentsDiagramsDirectory = join(repositoryRootPath, ".agents", "diagrams");

  await mkdir(docsDiagramsDirectory, { recursive: true });
  await mkdir(agentsDiagramsDirectory, { recursive: true });

  for (const targetModule of detectedModules) {
    const markdownContent = generateModuleDiagramMarkdown(
      targetModule,
      allExtractedSymbols,
      allExtractedDependencies,
      detectedModules,
    );

    const safeFileName = `${sanitizeModuleNameForFileName(targetModule.moduleName)}.md`;

    const docsFilePath = join(docsDiagramsDirectory, safeFileName);
    const agentsFilePath = join(agentsDiagramsDirectory, safeFileName);

    await writeFile(docsFilePath, markdownContent, "utf-8");
    await writeFile(agentsFilePath, markdownContent, "utf-8");
  }

  logInformation(
    `Diagrams generated: Flowchart and Sequence diagrams created for ${detectedModules.length} module(s) in docs/diagrams and .agents/diagrams`,
  );
}
