/**
 * Symbol registry generator.
 *
 * Generates a clean, compact markdown file containing all extracted symbol names
 * grouped by module and symbol kind, without file paths or line numbers.
 * This is used as the Tier 1 always-loaded context for AI agents.
 */

import type { ExtractedSymbol, DetectedModule } from "../contracts/index.js";

const KIND_TO_PLURAL_HEADER: Record<string, string> = {
  class: "Classes",
  function: "Functions",
  method: "Methods",
  interface: "Interfaces",
  enum: "Enums",
  variable: "Variables",
  constant: "Constants",
  route: "Routes",
  component: "Components",
  hook: "Hooks",
  namespace: "Namespaces",
  type_alias: "Types",
  decorator: "Decorators",
};

/**
 * Generate a compact markdown registry of all symbols grouped by module and kind.
 */
export function generateSymbolRegistryMarkdown(
  detectedModules: DetectedModule[],
  allExtractedSymbols: ExtractedSymbol[],
): string {
  const lines: string[] = [];

  lines.push("# Symbol Registry");
  lines.push("<!-- Auto-generated by project-index. Do not edit manually. -->");
  lines.push("");

  // Sort modules: root first, then by name alphabetically
  const sortedModules = [...detectedModules].sort((moduleA, moduleB) => {
    if (moduleA.moduleName === "root") return -1;
    if (moduleB.moduleName === "root") return 1;
    return moduleA.moduleName.localeCompare(moduleB.moduleName);
  });

  for (const module of sortedModules) {
    const moduleSymbols = allExtractedSymbols.filter(
      (symbol) => symbol.moduleName === module.moduleName,
    );

    // If there are no symbols in this module, skip it (unless it is root)
    if (moduleSymbols.length === 0 && module.moduleName !== "root") {
      continue;
    }

    lines.push(`## Module: ${module.moduleName}`);
    if (module.purpose) {
      lines.push(`> ${module.purpose}`);
      lines.push("");
    }

    // Group symbols by kind
    const symbolsByKind = new Map<string, ExtractedSymbol[]>();
    for (const symbol of moduleSymbols) {
      const pluralHeader = KIND_TO_PLURAL_HEADER[symbol.symbolKind] ?? "Other Symbols";
      const list = symbolsByKind.get(pluralHeader) ?? [];
      list.push(symbol);
      symbolsByKind.set(pluralHeader, list);
    }

    // Sort headers: Classes first, then Functions, then Interfaces, then others alphabetically
    const sortedHeaders = [...symbolsByKind.keys()].sort((headerA, headerB) => {
      const priority = (headerName: string) => {
        if (headerName === "Classes") return 1;
        if (headerName === "Functions") return 2;
        if (headerName === "Interfaces") return 3;
        return 4;
      };
      const priorityA = priority(headerA);
      const priorityB = priority(headerB);

      if (priorityA !== priorityB) {
        return priorityA - priorityB;
      }
      return headerA.localeCompare(headerB);
    });

    if (moduleSymbols.length === 0) {
      lines.push("_No symbols extracted._");
      lines.push("");
    } else {
      for (const header of sortedHeaders) {
        lines.push(`### ${header}`);
        const symbols = symbolsByKind.get(header) ?? [];
        // Sort symbols alphabetically by name
        symbols.sort((symbolA, symbolB) => symbolA.symbolName.localeCompare(symbolB.symbolName));
        for (const symbol of symbols) {
          lines.push(`- ${symbol.symbolName}`);
        }
        lines.push("");
      }
    }

    lines.push("---");
    lines.push("");
  }

  // Remove the trailing separator line
  if (lines.length > 0 && lines[lines.length - 2] === "---") {
    lines.splice(lines.length - 2, 2);
  }

  return lines.join("\n").trim() + "\n";
}
